### ISSUE TITLE
Cannot pickle 'Environment' object

### ISSUE THREAD

**Issue by jacklion710** [acids-ircam/RAVE#167]
Any idea what this error means? It came up when I tried to train using this line `rave train --config v2 --db_path C:/Users/Jake/Desktop/Dataset --name jl-sounds-study`

Log:
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "C:\Users\Jake\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jake\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jake\anaconda3\Scripts\rave.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jake\anaconda3\lib\site-packages\scripts\main_cli.py", line 28, in main
    app.run(train.main)
  File "C:\Users\Jake\anaconda3\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\Jake\anaconda3\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Jake\anaconda3\lib\site-packages\scripts\train.py", line 141, in main
    trainer.fit(model, train, val, ckpt_path=run)
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1103, in _run
    results = self._run_stage()
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1182, in _run_stage
    self._run_train()
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\loops\loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 84, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "C:\Users\Jake\anaconda3\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "C:\Users\Jake\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "C:\Users\Jake\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Jake\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "C:\Users\Jake\anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Jake\anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Jake\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Jake\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Jake\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jake\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Jake\anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by 50NNY1** [comment]
running into a very similar issue...
running: `rave train --config v2 --db_path documents/dev/rave --name pansonicv1`
error:
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/scripts/main_cli.py", line 28, in main
    app.run(train.main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/scripts/train.py", line 141, in main
    trainer.fit(model, train, val, ckpt_path=run)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 84, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1034, in __init__
    w.start()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object

**Comment by caillonantoine** [comment]
Fixed for now (hopefully), I'll work on a more optimal solution later !

**Comment by 50NNY1** [comment]
i am afraid the issue still exists!

error below:
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/scripts/main_cli.py", line 28, in main
    app.run(train.main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/scripts/train.py", line 141, in main
    trainer.fit(model, train, val, ckpt_path=run)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 84, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1034, in __init__
    w.start()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object

**Comment by 50NNY1** [comment]
Im afriad the issue still exists. I'll include the whole terminal output from running `rave train`
Error:
I0130 14:03:00.239748 8022866560 resource_reader.py:50] system_path_file_exists:v2.gin
E0130 14:03:00.239948 8022866560 resource_reader.py:55] Path not found: v2.gin
I0130 14:03:00.239983 8022866560 resource_reader.py:50] system_path_file_exists:/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/rave/v2.gin
E0130 14:03:00.240005 8022866560 resource_reader.py:55] Path not found: /opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/rave/v2.gin
I0130 14:03:00.240538 8022866560 resource_reader.py:50] system_path_file_exists:configs/v1.gin
E0130 14:03:00.240666 8022866560 resource_reader.py:55] Path not found: configs/v1.gin
RAVE(
  (pqmf): CachedPQMF(
    (forward_conv): Conv1d(1, 16, kernel_size=(513,), stride=(16,), bias=False)
    (inverse_conv): Conv1d(16, 16, kernel_size=(33,), stride=(1,), bias=False)
  )
  (encoder): VariationalEncoder(
    (encoder): EncoderV2(
      (net): CachedSequential(
        (0): Conv1d(16, 96, kernel_size=(7,), stride=(1,), bias=False)
        (1): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (2): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (3): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (4): LeakyReLU(negative_slope=0.2)
        (5): Conv1d(96, 192, kernel_size=(8,), stride=(4,), bias=False)
        (6): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (7): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (8): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (9): LeakyReLU(negative_slope=0.2)
        (10): Conv1d(192, 384, kernel_size=(8,), stride=(4,), bias=False)
        (11): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (12): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (13): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (14): LeakyReLU(negative_slope=0.2)
        (15): Conv1d(384, 768, kernel_size=(8,), stride=(4,), bias=False)
        (16): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (17): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (18): Residual(
          (aligned): Branches(
            (branches): ModuleList(
              (0): DilatedUnit(
                (net): CachedSequential(
                  (0): LeakyReLU(negative_slope=0.2)
                  (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                  (2): LeakyReLU(negative_slope=0.2)
                  (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
                )
              )
              (1): Identity()
            )
          )
        )
        (19): LeakyReLU(negative_slope=0.2)
        (20): Conv1d(768, 1536, kernel_size=(4,), stride=(2,), bias=False)
        (21): LeakyReLU(negative_slope=0.2)
        (22): Conv1d(1536, 256, kernel_size=(3,), stride=(1,), bias=False)
      )
    )
  )
  (decoder): GeneratorV2(
    (net): CachedSequential(
      (0): Conv1d(128, 1536, kernel_size=(3,), stride=(1,), bias=False)
      (1): LeakyReLU(negative_slope=0.2)
      (2): ConvTranspose1d(1536, 768, kernel_size=(4,), stride=(2,), padding=(1,), bias=False)
      (3): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (4): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (5): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(768, 768, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(768, 768, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (6): LeakyReLU(negative_slope=0.2)
      (7): ConvTranspose1d(768, 384, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (8): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (9): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (10): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(384, 384, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(384, 384, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (11): LeakyReLU(negative_slope=0.2)
      (12): ConvTranspose1d(384, 192, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (13): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (14): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (15): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(192, 192, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(192, 192, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (16): LeakyReLU(negative_slope=0.2)
      (17): ConvTranspose1d(192, 96, kernel_size=(8,), stride=(4,), padding=(2,), bias=False)
      (18): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (19): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(3,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (20): Residual(
        (aligned): Branches(
          (branches): ModuleList(
            (0): DilatedUnit(
              (net): CachedSequential(
                (0): LeakyReLU(negative_slope=0.2)
                (1): Conv1d(96, 96, kernel_size=(3,), stride=(1,), dilation=(9,), bias=False)
                (2): LeakyReLU(negative_slope=0.2)
                (3): Conv1d(96, 96, kernel_size=(1,), stride=(1,), bias=False)
              )
            )
            (1): Identity()
          )
        )
      )
      (21): LeakyReLU(negative_slope=0.2)
      (22): Conv1d(96, 16, kernel_size=(7,), stride=(1,), bias=False)
    )
  )
  (discriminator): CombineDiscriminators(
    (discriminators): ModuleList(
      (0): MultiPeriodDiscriminator(
        (layers): ModuleList(
          (0): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (1): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (2): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (3): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
          (4): ConvNet(
            (net): Sequential(
              (0): Conv2d(1, 96, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv2d(96, 192, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv2d(192, 384, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv2d(384, 768, kernel_size=(5, 1), stride=(4, 1), padding=(2, 0))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv2d(768, 1, kernel_size=(1, 1), stride=(1, 1))
            )
          )
        )
      )
      (1): MultiScaleDiscriminator(
        (layers): ModuleList(
          (0): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
          (1): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
          (2): ConvNet(
            (net): Sequential(
              (0): Conv1d(1, 96, kernel_size=(15,), stride=(4,), padding=(7,))
              (1): LeakyReLU(negative_slope=0.2)
              (2): Conv1d(96, 192, kernel_size=(15,), stride=(4,), padding=(7,))
              (3): LeakyReLU(negative_slope=0.2)
              (4): Conv1d(192, 384, kernel_size=(15,), stride=(4,), padding=(7,))
              (5): LeakyReLU(negative_slope=0.2)
              (6): Conv1d(384, 768, kernel_size=(15,), stride=(4,), padding=(7,))
              (7): LeakyReLU(negative_slope=0.2)
              (8): Conv1d(768, 1, kernel_size=(1,), stride=(1,))
            )
          )
        )
      )
    )
  )
  (audio_distance): AudioDistanceV1(
    (multiscale_stft): MultiScaleSTFT(
      (stfts): ModuleList(
        (0): Spectrogram()
        (1): Spectrogram()
        (2): Spectrogram()
        (3): Spectrogram()
        (4): Spectrogram()
      )
      (mel_scales): ModuleList(
        (0): None
        (1): None
        (2): None
        (3): None
        (4): None
      )
    )
  )
  (multiband_audio_distance): AudioDistanceV1(
    (multiscale_stft): MultiScaleSTFT(
      (stfts): ModuleList(
        (0): Spectrogram()
        (1): Spectrogram()
        (2): Spectrogram()
        (3): Spectrogram()
        (4): Spectrogram()
      )
      (mel_scales): ModuleList(
        (0): None
        (1): None
        (2): None
        (3): None
        (4): None
      )
    )
  )
)
train set: 2511 examples
val set: 52 examples
selected gpu: []
/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:467: LightningDeprecationWarning: Setting `Trainer(gpus=[])` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=[])` instead.
  rank_zero_deprecation(
GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:200: UserWarning: MPS available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='mps', devices=1)`.
  rank_zero_warn(

  | Name                     | Type                  | Params
-------------------------------------------------------------------
0 | pqmf                     | CachedPQMF            | 16.7 K
1 | encoder                  | VariationalEncoder    | 18.4 M
2 | decoder                  | GeneratorV2           | 17.8 M
3 | discriminator            | CombineDiscriminators | 27.1 M
4 | audio_distance           | AudioDistanceV1       | 0
5 | multiband_audio_distance | AudioDistanceV1       | 0
-------------------------------------------------------------------
63.4 M    Trainable params
0         Non-trainable params
63.4 M    Total params
253.578   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/scripts/main_cli.py", line 28, in main
    app.run(train.main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/scripts/train.py", line 141, in main
    trainer.fit(model, train, val, ckpt_path=run)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 84, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1034, in __init__
    w.start()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/rave/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object

**Comment by 50NNY1** [comment]
> 

posix

**Comment by caillonantoine** [comment]
Oh you are training on a mac ! Ok so this isn't supported yet, unfortunately. To train RAVE you need a supported accelerator (usually a GPU). PyTorch is about to support the MPS backend (the mac GPU), and I'll update RAVE when it is done !z

**Comment by 50NNY1** [comment]
lovely stuff cheers !!!

**Comment by 50NNY1** [comment]
moved onto my windows machine to, still running into very similar issues 
```
  File "C:\Users\sonny\miniconda3\envs\rave\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sonny\miniconda3\envs\rave\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\sonny\miniconda3\envs\rave\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

and to run `python -c "import os;print(os.name)"` again it returns:
nt

**Comment by jacklion710** [comment]
Can confirm that the same issue persists on windows after reinstalling this morning.

**Comment by caillonantoine** [comment]
It should be fixed now. Can you give it a try ?

**Comment by jacklion710** [comment]
Awesome, seems to have fixed this issue for me! It is currently training now

**Comment by 50NNY1** [comment]
works! brilliant
