### ISSUE TITLE
Error when training prior

### ISSUE THREAD

**Issue by moiseshorta** [acids-ircam/RAVE#45]
Hi,

I'm experiencing troubles with training the prior, similar error as described in closed issue #33 . I'm reopening the issue, as I dont think it was completely solved.

Basically get the same Runtime error, as described here. Training of RAVE was done with custom parameters, but can't seem to access them as there was no `instructions_*.txt `generated when working with the `cli_helper.py`

`RuntimeError: cannot reshape tensor of 0 elements into shape [8, 0, 128, -1] because the unspecified dimension size -1 can be any value and is ambiguous`

Thanks!

**Comment by caillonantoine** [comment]
You can see the parameters in `runs/NAME/rave/version_XX/hparams.json`, can you post them here ?

**Comment by moiseshorta** [comment]
Good to know, here are the params:

```
bias: true
capacity: 64
cropped_latent_size: 128
d_capacity: 16
d_multiplier: 4
d_n_layers: 4
data_size: 16
feature_match: true
latent_size: 128
loud_stride: 1
max_kl: 0.1
min_kl: 0.1
mode: hinge
no_latency: true
noise_bands: 5
noise_ratios:
- 4
- 4
- 4
ratios:
- 4
- 4
- 4
- 2
sr: 48000
use_noise: true
warmup: 7000000
```

**Comment by caillonantoine** [comment]
Can you post the full traceback ?

**Comment by moiseshorta** [comment]
Sure, here it is:

`Traceback (most recent call last): File "/home/moises/Desktop/AI/RAVE_realtime/RAVE/train_prior.py", line 122, in <module> trainer.fit(model, train, val) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit self._run(model) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run self._dispatch() File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch self.accelerator.start_training(self) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training self.training_type_plugin.start_training(trainer) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training self._results = trainer.run_stage() File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage return self._run_train() File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_train self._run_sanity_check(self.lightning_module) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1122, in _run_sanity_check self._evaluation_loop.run() File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run self.advance(*args, **kwargs) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance dl_outputs = self.epoch_loop.run( File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run self.advance(*args, **kwargs) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance output = self.evaluation_step(batch, batch_idx, dataloader_idx) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 158, in evaluation_step output = self.trainer.accelerator.validation_step(step_kwargs) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step return self.training_type_plugin.validation_step(*step_kwargs.values()) File "/home/moises/anaconda3/envs/rave_realtime/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 178, in validation_step return self.model.validation_step(*args, **kwargs) File "/home/moises/Desktop/AI/RAVE_realtime/RAVE/prior/model.py", line 147, in validation_step x = torch.argmax(self.split_classes(x[..., 1:]), -1) File "/home/moises/Desktop/AI/RAVE_realtime/RAVE/prior/model.py", line 107, in split_classes x = x.reshape(x.shape[0], x.shape[1], self.data_size, -1) RuntimeError: cannot reshape tensor of 0 elements into shape [8, 0, 128, -1] because the unspecified dimension size -1 can be any value and is ambiguous`

**Comment by caillonantoine** [comment]
Should be fixed in d9f55f59627ea02689578d0ddae05b420be8d4d2 can you check ?

**Comment by caillonantoine** [comment]
Could you provide me the total duration of your dataset ?

**Comment by iamzoltan** [comment]
> Should be fixed in [d9f55f5](https://github.com/acids-ircam/RAVE/commit/d9f55f59627ea02689578d0ddae05b420be8d4d2) can you check ?

I just exported a newly completed rave model, and I am still getting this error, even with the latest code. any ideas?

**Comment by caillonantoine** [comment]
I still need to know the duration of your dataset

**Comment by iamzoltan** [comment]
its just under an hour in total

**Comment by moiseshorta** [comment]
> Could you provide me the total duration of your dataset ?

It was about 2hrs approximately. I haven't been able to verity the fix though.

**Comment by caillonantoine** [comment]
Mhh it is really not enough but I'm not sure if the problem is coming from that... Could you check the shape of the tensors in the validation step ?

**Comment by iamzoltan** [comment]
this makes me think that the array slicing that gets passed into the `split_classes` method omits all the data. does that make sense?

**Comment by caillonantoine** [comment]
ooooooooh I see
You have set the cropped latent size to 128 (which is btw not a very good idea haha) ! Because of the diagonal shift the quantized tensor has only 1 timestep, which results in an ambiguous tensor size in the end.

**Comment by iamzoltan** [comment]
I don't remember setting that anywhere haha, how do I fix it? Is this a prior model issue? or does it stem from my rave model? (which the rave model seems to be doing a decent job on reconstruction)

**Comment by caillonantoine** [comment]
yep it comes from the rave model ! You may have entered it during the cli_helper phase ! What is the estimated latent space dimensionality ?

**Comment by iamzoltan** [comment]
do you mean the 0.95 manifold? it looks like the last value is 6

**Comment by iamzoltan** [comment]
that didnt work, I had to change the `else` block with the above line. The prior is now training! thanks :) how do I avoid this going forward?

**Comment by caillonantoine** [comment]
Ok that is pretty weird
I am not sure where the problem is coming from
